.TH "_caribou_queue_t" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_caribou_queue_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "\fBcaribou_queue_msg_t\fP ** \fBmsgs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file queue\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int _caribou_queue_t::count"

.PP
Definition at line 35 of file queue\&.h\&.
.SS "int _caribou_queue_t::depth"

.PP
Definition at line 34 of file queue\&.h\&.
.SS "\fBcaribou_queue_msg_t\fP** _caribou_queue_t::msgs"

.PP
Definition at line 36 of file queue\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
