.TH "include/caribou Directory Reference" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/caribou Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdev\fP"
.br
.ti -1c
.RI "directory \fBkernel\fP"
.br
.ti -1c
.RI "directory \fBlib\fP"
.br
.in -1c
