.TH "src/dev/adc.c" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dev/adc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/dev/adc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcaribou_adc_start\fP (\fBcaribou_adc_t\fP *adc)"
.br
.ti -1c
.RI "int \fBcaribou_adc_ready\fP (\fBcaribou_adc_t\fP *adc)"
.br
.ti -1c
.RI "chip_adc_value_t \fBcaribou_adc_value\fP (\fBcaribou_adc_t\fP *adc)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.PP
\fBAuthor:\fP
.RS 4
Mike Sharkey mike@pikeaero.com\&. 
.RE
.PP
\fBCopyright:\fP
.RS 4
© 2005-2013 by Pike Aerospace Research Corporation 
.PP
© 2014-2015 by Mike Sharkey
.RE
.PP
This file is part of CARIBOU RTOS CARIBOU RTOS is free software: you can redistribute it and/or modify it under the terms of the Beerware License Version 43\&. 'THE BEER-WARE LICENSE' (Revision 43): Mike Sharkey mike@pikeaero.com wrote this file\&. As long as you retain this notice you can do whatever you want with this stuff\&. If we meet some day, and you think this stuff is worth it, you can buy me a beer in return ~ Mike Sharkey 
.PP
Definition in file \fBadc\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int caribou_adc_ready (\fBcaribou_adc_t\fP *adc)"

.PP
Definition at line 22 of file adc\&.c\&.
.SS "int caribou_adc_start (\fBcaribou_adc_t\fP *adc)"

.PP
Definition at line 17 of file adc\&.c\&.
.SS "chip_adc_value_t caribou_adc_value (\fBcaribou_adc_t\fP *adc)"

.PP
Definition at line 27 of file adc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
