.TH "caribou_uart_config_t" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
caribou_uart_config_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uart\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcaribou_uart_baud_t\fP \fBbaud_rate\fP"
.br
.ti -1c
.RI "\fBcaribou_uart_word_t\fP \fBword_size\fP"
.br
.ti -1c
.RI "\fBcaribou_uart_stop_t\fP \fBstop_bits\fP"
.br
.ti -1c
.RI "\fBcaribou_uart_parity_t\fP \fBparity_bits\fP"
.br
.ti -1c
.RI "\fBcaribou_uart_flow_t\fP \fBflow_control\fP"
.br
.ti -1c
.RI "\fBcaribou_uart_dma_t\fP \fBdma_mode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file uart\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBcaribou_uart_baud_t\fP caribou_uart_config_t::baud_rate"

.PP
Definition at line 129 of file uart\&.h\&.
.SS "\fBcaribou_uart_dma_t\fP caribou_uart_config_t::dma_mode"

.PP
Definition at line 134 of file uart\&.h\&.
.SS "\fBcaribou_uart_flow_t\fP caribou_uart_config_t::flow_control"

.PP
Definition at line 133 of file uart\&.h\&.
.SS "\fBcaribou_uart_parity_t\fP caribou_uart_config_t::parity_bits"

.PP
Definition at line 132 of file uart\&.h\&.
.SS "\fBcaribou_uart_stop_t\fP caribou_uart_config_t::stop_bits"

.PP
Definition at line 131 of file uart\&.h\&.
.SS "\fBcaribou_uart_word_t\fP caribou_uart_config_t::word_size"

.PP
Definition at line 130 of file uart\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
