.TH "caribou_bytequeue_t" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
caribou_bytequeue_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bytequeue\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBqueue\fP"
.br
.ti -1c
.RI "uint16_t \fBsize\fP"
.br
.RI "\fIThe receive buffer\&. \fP"
.ti -1c
.RI "uint16_t \fBhead\fP"
.br
.RI "\fIThe receive buffer size\&. \fP"
.ti -1c
.RI "uint16_t \fBtail\fP"
.br
.RI "\fIThe receive buffer head pointer\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Byte queues\&. 
.PP
Definition at line 29 of file bytequeue\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t caribou_bytequeue_t::head"

.PP
The receive buffer size\&. 
.PP
Definition at line 33 of file bytequeue\&.h\&.
.SS "uint8_t* caribou_bytequeue_t::queue"

.PP
Definition at line 31 of file bytequeue\&.h\&.
.SS "uint16_t caribou_bytequeue_t::size"

.PP
The receive buffer\&. 
.PP
Definition at line 32 of file bytequeue\&.h\&.
.SS "uint16_t caribou_bytequeue_t::tail"

.PP
The receive buffer head pointer\&. 
.PP
Definition at line 34 of file bytequeue\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
