.TH "include/caribou.h" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/caribou.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou_config\&.h>\fP
.br
\fC#include <board\&.h>\fP
.br
\fC#include <caribou/kernel/types\&.h>\fP
.br
\fC#include <caribou/kernel/timer\&.h>\fP
.br
\fC#include <caribou/kernel/thread\&.h>\fP
.br
\fC#include <caribou/kernel/interrupt\&.h>\fP
.br
\fC#include <caribou/lib/bytequeue\&.h>\fP
.br
\fC#include <caribou/lib/cbmath\&.h>\fP
.br
\fC#include <caribou/lib/errno\&.h>\fP
.br
\fC#include <caribou/lib/fault\&.h>\fP
.br
\fC#include <caribou/lib/heap\&.h>\fP
.br
\fC#include <caribou/lib/mutex\&.h>\fP
.br
\fC#include <caribou/lib/qsort\&.h>\fP
.br
\fC#include <caribou/lib/queue\&.h>\fP
.br
\fC#include <caribou/lib/rand\&.h>\fP
.br
\fC#include <caribou/lib/semaphore\&.h>\fP
.br
\fC#include <caribou/lib/spinlock\&.h>\fP
.br
\fC#include <caribou/lib/stdarg\&.h>\fP
.br
\fC#include <caribou/lib/stddef\&.h>\fP
.br
\fC#include <caribou/lib/stdint\&.h>\fP
.br
\fC#include <caribou/lib/stdio\&.h>\fP
.br
\fC#include <caribou/lib/string\&.h>\fP
.br
\fC#include <caribou/dev/adc\&.h>\fP
.br
\fC#include <caribou/dev/gpio\&.h>\fP
.br
\fC#include <caribou/dev/i2c\&.h>\fP
.br
\fC#include <caribou/dev/i2s\&.h>\fP
.br
\fC#include <caribou/dev/spi\&.h>\fP
.br
\fC#include <caribou/dev/uart\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CARIBOU_RTOS__\fP"
.br
.ti -1c
.RI "#define \fBCARIBOU_VERSION\fP   '0\&.9\&.5'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcaribou_lock_state\fP ()"
.br
.RI "\fITest the state of the CARIBOU scheduler lock\&. \fP"
.ti -1c
.RI "int \fBcaribou_lock\fP ()"
.br
.RI "\fILock the CARIBOU scheduler onto current thread\&. \fP"
.ti -1c
.RI "int \fBcaribou_unlock\fP ()"
.br
.RI "\fIUnlock the CARIBOU scheduler\&. \fP"
.ti -1c
.RI "void \fBcaribou_lock_set\fP (int state)"
.br
.RI "\fISet the CARIBOU scheduler lock state\&. \fP"
.ti -1c
.RI "void \fBcaribou_preempt\fP ()"
.br
.RI "\fIForce scheduler to perform a context switch\&. \fP"
.ti -1c
.RI "void \fBcaribou_exec\fP (void)"
.br
.RI "\fIThe CARIBOU main thread loop\&. \fBcaribou_exec()\fP does not return\&. \fP"
.ti -1c
.RI "void \fBcaribou_init_clock\fP ()"
.br
.RI "\fIInitialize the clock such that jiffies start ticking\&. \fP"
.ti -1c
.RI "void \fBcaribou_init\fP (int8_t priority)"
.br
.RI "\fIInitialize the CARIBOU main thread\&. \fP"
.ti -1c
.RI "const char * \fBcaribou_version\fP ()"
.br
.ti -1c
.RI "void \fBcaribou_early_init\fP (void)"
.br
.RI "\fIA hook to perform early board initialization\&. Static stacks are initialized, BSS is \fINOT\fP initialized at this stage\&. \fP"
.ti -1c
.RI "void \fBcaribou_late_init\fP (void)"
.br
.RI "\fIA hook to perform late initialization\&. Static stacks, BSS, heap, and static contructors are all initialized at this stage\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
.PP
\fBAuthor:\fP
.RS 4
Mike Sharkey mike@pikeaero.com\&. 
.RE
.PP
\fBCopyright:\fP
.RS 4
© 2005-2013 by Pike Aerospace Research Corporation 
.PP
© 2014-2015 by Mike Sharkey
.RE
.PP
This file is part of CARIBOU RTOS CARIBOU RTOS is free software: you can redistribute it and/or modify it under the terms of the Beerware License Version 43\&. 'THE BEER-WARE LICENSE' (Revision 43): Mike Sharkey mike@pikeaero.com wrote this file\&. As long as you retain this notice you can do whatever you want with this stuff\&. If we meet some day, and you think this stuff is worth it, you can buy me a beer in return ~ Mike Sharkey 
.PP
Definition in file \fBcaribou\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define __CARIBOU_RTOS__"

.PP
Definition at line 57 of file caribou\&.h\&.
.SS "#define CARIBOU_VERSION   '0\&.9\&.5'"

.PP
Definition at line 60 of file caribou\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void caribou_early_init (void)"

.PP
A hook to perform early board initialization\&. Static stacks are initialized, BSS is \fINOT\fP initialized at this stage\&. 
.SS "void caribou_exec (void)"

.PP
The CARIBOU main thread loop\&. \fBcaribou_exec()\fP does not return\&. 
.PP
\fBNote:\fP
.RS 4
If it is desired to run some application code from the main thread, then it is recommended that the application code implement the main_idle() function which is callback from the main thread idle loop, and will be called after each cycle of CARIBOU house keeping\&. 
.RE
.PP
never to return\&. 
.PP
Definition at line 90 of file caribou\&.c\&.
.SS "void caribou_init (int8_tpriority)"

.PP
Initialize the CARIBOU main thread\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpriority\fP The priority to assign to the main thread\&. 
.RE
.PP
\fBNote:\fP
.RS 4
Interrupts are disabled for the duration of this function\&. 
.PP
\fBcaribou_init()\fP must be called before any other CARIBOU threads are created\&. 
.RE
.PP

.PP
Definition at line 115 of file caribou\&.c\&.
.SS "void caribou_init_clock ()"

.PP
Initialize the clock such that jiffies start ticking\&. 
.PP
Definition at line 98 of file caribou\&.c\&.
.SS "void caribou_late_init (void)"

.PP
A hook to perform late initialization\&. Static stacks, BSS, heap, and static contructors are all initialized at this stage\&. 
.SS "int caribou_lock ()"

.PP
Lock the CARIBOU scheduler onto current thread\&. 
.PP
 
.PP
Definition at line 40 of file caribou\&.c\&.
.SS "void caribou_lock_set (intstate)"

.PP
Set the CARIBOU scheduler lock state\&. 
.PP
 
.PP
Definition at line 56 of file caribou\&.c\&.
.SS "int caribou_lock_state ()"

.PP
Test the state of the CARIBOU scheduler lock\&. 
.PP
 
.PP
\fBReturns:\fP
.RS 4
The number of lock state 
.RE
.PP

.PP
Definition at line 32 of file caribou\&.c\&.
.SS "void caribou_preempt ()"

.PP
Force scheduler to perform a context switch\&. 
.PP
 
.PP
Definition at line 64 of file caribou\&.c\&.
.SS "int caribou_unlock ()"

.PP
Unlock the CARIBOU scheduler\&. 
.PP
 
.PP
Definition at line 48 of file caribou\&.c\&.
.SS "const char* caribou_version ()"

.PP
 
.PP
\fBReturns:\fP
.RS 4
The Caribou Version\&. 
.RE
.PP

.PP
Definition at line 21 of file caribou\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
