.TH "caribou_mutex_t" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
caribou_mutex_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mutex\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBthread\fP"
.br
.ti -1c
.RI "uint16_t \fBlocks\fP"
.br
.ti -1c
.RI "uint8_t \fBflags\fP"
.br
.ti -1c
.RI "uint8_t \fBblocking\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file mutex\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t caribou_mutex_t::blocking"

.PP
Definition at line 35 of file mutex\&.h\&.
.SS "uint8_t caribou_mutex_t::flags"

.PP
Definition at line 34 of file mutex\&.h\&.
.SS "uint16_t caribou_mutex_t::locks"

.PP
Definition at line 33 of file mutex\&.h\&.
.SS "void* caribou_mutex_t::thread"

.PP
Definition at line 32 of file mutex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
