.TH "caribou_spi_t" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
caribou_spi_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "chip_spi_port_t \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file spi\&.h\&.
.SH "Field Documentation"
.PP 
.SS "chip_spi_port_t caribou_spi_t::port"

.PP
Definition at line 28 of file spi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
