.TH "src/lib/errno.c" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib/errno.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/lib/errno\&.h>\fP
.br
\fC#include <caribou/kernel/thread\&.h>\fP
.br
\fC#include <caribou/lib/stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBstrerror\fP (int errnum)"
.br
.ti -1c
.RI "void \fBperror\fP (char *s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBerrno_t\fP \fBerrno\fP =0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.PP
\fBAuthor:\fP
.RS 4
Mike Sharkey mike@pikeaero.com\&. 
.RE
.PP
\fBCopyright:\fP
.RS 4
© 2005-2013 by Pike Aerospace Research Corporation 
.PP
© 2014-2015 by Mike Sharkey
.RE
.PP
This file is part of CARIBOU RTOS CARIBOU RTOS is free software: you can redistribute it and/or modify it under the terms of the Beerware License Version 43\&. 'THE BEER-WARE LICENSE' (Revision 43): Mike Sharkey mike@pikeaero.com wrote this file\&. As long as you retain this notice you can do whatever you want with this stuff\&. If we meet some day, and you think this stuff is worth it, you can buy me a beer in return ~ Mike Sharkey 
.PP
Definition in file \fBerrno\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void perror (char *s)"

.PP
Definition at line 174 of file errno\&.c\&.
.SS "char* strerror (interrnum)"

.PP
Definition at line 31 of file errno\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBerrno_t\fP errno =0"

.PP
Definition at line 19 of file errno\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
