.TH "include/caribou/dev/gpio.h" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/caribou/dev/gpio.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/kernel/types\&.h>\fP
.br
\fC#include <chip/gpio\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcaribou_gpio_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCARIBOU_GPIO_INIT\fP(port, pinmask)   {port,pinmask}"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_0\fP   (1<<0)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_1\fP   (1<<1)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_2\fP   (1<<2)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_3\fP   (1<<3)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_4\fP   (1<<4)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_5\fP   (1<<5)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_6\fP   (1<<6)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_7\fP   (1<<7)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_8\fP   (1<<8)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_9\fP   (1<<9)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_10\fP   (1<<10)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_11\fP   (1<<11)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_12\fP   (1<<12)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_13\fP   (1<<13)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_14\fP   (1<<14)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_15\fP   (1<<15)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_16\fP   (1<<16)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_17\fP   (1<<17)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_18\fP   (1<<18)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_19\fP   (1<<19)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_20\fP   (1<<20)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_21\fP   (1<<21)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_22\fP   (1<<22)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_23\fP   (1<<23)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_24\fP   (1<<24)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_25\fP   (1<<25)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_26\fP   (1<<26)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_27\fP   (1<<27)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_28\fP   (1<<28)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_29\fP   (1<<29)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_30\fP   (1<<30)"
.br
.ti -1c
.RI "#define \fBCARIBOU_GPIO_PIN_31\fP   (1<<31)"
.br
.ti -1c
.RI "#define \fBcaribou_gpio_set_output\fP(gpio)   chip_gpio_set_output((gpio)->port,(gpio)->pinmask)"
.br
.ti -1c
.RI "#define \fBcaribou_gpio_set_input\fP(gpio)   chip_gpio_set_input((gpio)->port,(gpio)->pinmask)"
.br
.ti -1c
.RI "#define \fBcaribou_gpio_set_pullup\fP(gpio)   chip_gpio_set_pullup((gpio)->port,(gpio)->pinmask)"
.br
.ti -1c
.RI "#define \fBcaribou_gpio_set_pulldown\fP(gpio)   chip_gpio_set_pulldown((gpio)->port,(gpio)->pinmask)"
.br
.ti -1c
.RI "#define \fBcaribou_gpio_toggle\fP(gpio)   chip_gpio_toggle((gpio)->port,(gpio)->pinmask)"
.br
.ti -1c
.RI "#define \fBcaribou_gpio_set\fP(gpio)   chip_gpio_set((gpio)->port,(gpio)->pinmask)"
.br
.ti -1c
.RI "#define \fBcaribou_gpio_reset\fP(gpio)   chip_gpio_reset((gpio)->port,(gpio)->pinmask)"
.br
.ti -1c
.RI "#define \fBcaribou_gpio_pinstate\fP(gpio)   chip_gpio_pinstate((gpio)->port,(gpio)->pinmask)"
.br
.ti -1c
.RI "#define \fBcaribou_gpio_pinmask\fP(gpio)   ((gpio)->pinmask)"
.br
.ti -1c
.RI "#define \fBcaribou_gpio_write\fP(gpio, state)   {if((state)) \fBcaribou_gpio_set\fP(gpio); else \fBcaribou_gpio_reset\fP(gpio);}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.PP
\fBAuthor:\fP
.RS 4
Mike Sharkey mike@pikeaero.com\&. 
.RE
.PP
\fBCopyright:\fP
.RS 4
© 2005-2013 by Pike Aerospace Research Corporation 
.PP
© 2014-2015 by Mike Sharkey
.RE
.PP
This file is part of CARIBOU RTOS CARIBOU RTOS is free software: you can redistribute it and/or modify it under the terms of the Beerware License Version 43\&. 'THE BEER-WARE LICENSE' (Revision 43): Mike Sharkey mike@pikeaero.com wrote this file\&. As long as you retain this notice you can do whatever you want with this stuff\&. If we meet some day, and you think this stuff is worth it, you can buy me a beer in return ~ Mike Sharkey 
.PP
Definition in file \fBgpio\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define CARIBOU_GPIO_INIT(port, pinmask)   {port,pinmask}"

.PP
Definition at line 36 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_0   (1<<0)"

.PP
Definition at line 38 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_1   (1<<1)"

.PP
Definition at line 39 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_10   (1<<10)"

.PP
Definition at line 48 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_11   (1<<11)"

.PP
Definition at line 49 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_12   (1<<12)"

.PP
Definition at line 50 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_13   (1<<13)"

.PP
Definition at line 51 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_14   (1<<14)"

.PP
Definition at line 52 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_15   (1<<15)"

.PP
Definition at line 53 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_16   (1<<16)"

.PP
Definition at line 54 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_17   (1<<17)"

.PP
Definition at line 55 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_18   (1<<18)"

.PP
Definition at line 56 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_19   (1<<19)"

.PP
Definition at line 57 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_2   (1<<2)"

.PP
Definition at line 40 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_20   (1<<20)"

.PP
Definition at line 58 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_21   (1<<21)"

.PP
Definition at line 59 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_22   (1<<22)"

.PP
Definition at line 60 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_23   (1<<23)"

.PP
Definition at line 61 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_24   (1<<24)"

.PP
Definition at line 62 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_25   (1<<25)"

.PP
Definition at line 63 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_26   (1<<26)"

.PP
Definition at line 64 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_27   (1<<27)"

.PP
Definition at line 65 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_28   (1<<28)"

.PP
Definition at line 66 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_29   (1<<29)"

.PP
Definition at line 67 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_3   (1<<3)"

.PP
Definition at line 41 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_30   (1<<30)"

.PP
Definition at line 68 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_31   (1<<31)"

.PP
Definition at line 69 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_4   (1<<4)"

.PP
Definition at line 42 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_5   (1<<5)"

.PP
Definition at line 43 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_6   (1<<6)"

.PP
Definition at line 44 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_7   (1<<7)"

.PP
Definition at line 45 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_8   (1<<8)"

.PP
Definition at line 46 of file gpio\&.h\&.
.SS "#define CARIBOU_GPIO_PIN_9   (1<<9)"

.PP
Definition at line 47 of file gpio\&.h\&.
.SS "#define caribou_gpio_pinmask(gpio)   ((gpio)->pinmask)"

.PP
Definition at line 79 of file gpio\&.h\&.
.SS "#define caribou_gpio_pinstate(gpio)   chip_gpio_pinstate((gpio)->port,(gpio)->pinmask)"

.PP
Definition at line 78 of file gpio\&.h\&.
.SS "#define caribou_gpio_reset(gpio)   chip_gpio_reset((gpio)->port,(gpio)->pinmask)"

.PP
Definition at line 77 of file gpio\&.h\&.
.SS "#define caribou_gpio_set(gpio)   chip_gpio_set((gpio)->port,(gpio)->pinmask)"

.PP
Definition at line 76 of file gpio\&.h\&.
.SS "#define caribou_gpio_set_input(gpio)   chip_gpio_set_input((gpio)->port,(gpio)->pinmask)"

.PP
Definition at line 72 of file gpio\&.h\&.
.SS "#define caribou_gpio_set_output(gpio)   chip_gpio_set_output((gpio)->port,(gpio)->pinmask)"

.PP
Definition at line 71 of file gpio\&.h\&.
.SS "#define caribou_gpio_set_pulldown(gpio)   chip_gpio_set_pulldown((gpio)->port,(gpio)->pinmask)"

.PP
Definition at line 74 of file gpio\&.h\&.
.SS "#define caribou_gpio_set_pullup(gpio)   chip_gpio_set_pullup((gpio)->port,(gpio)->pinmask)"

.PP
Definition at line 73 of file gpio\&.h\&.
.SS "#define caribou_gpio_toggle(gpio)   chip_gpio_toggle((gpio)->port,(gpio)->pinmask)"

.PP
Definition at line 75 of file gpio\&.h\&.
.SS "#define caribou_gpio_write(gpio, state)   {if((state)) \fBcaribou_gpio_set\fP(gpio); else \fBcaribou_gpio_reset\fP(gpio);}"

.PP
Definition at line 80 of file gpio\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
