.TH "heap_state_t" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
heap_state_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bitmap_heap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t * \fBheap_free_bitmap\fP"
.br
.ti -1c
.RI "uint32_t * \fBheap_last_bitmap\fP"
.br
.ti -1c
.RI "int32_t \fBheap_bitmap_size\fP"
.br
.ti -1c
.RI "uint8_t * \fBheap_area\fP"
.br
.ti -1c
.RI "int32_t \fBheap_blocks\fP"
.br
.ti -1c
.RI "int32_t \fBheap_blocks_allocated\fP"
.br
.ti -1c
.RI "uint32_t \fBheap_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BITMAP_HEAP state variables\&. 
.PP
Definition at line 47 of file bitmap_heap\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t* heap_state_t::heap_area"
Pointer to the first bytes of the usable heap memory 
.PP
Definition at line 59 of file bitmap_heap\&.h\&.
.SS "int32_t heap_state_t::heap_bitmap_size"
The size of each heap bitmap in bytes 
.PP
Definition at line 56 of file bitmap_heap\&.h\&.
.SS "int32_t heap_state_t::heap_blocks"
The size of the heap in blocks 
.PP
Definition at line 62 of file bitmap_heap\&.h\&.
.SS "int32_t heap_state_t::heap_blocks_allocated"
The number of blocks in use (for fast statistics) 
.PP
Definition at line 65 of file bitmap_heap\&.h\&.
.SS "uint32_t heap_state_t::heap_flags"
The mpu heap region flags 
.PP
Definition at line 68 of file bitmap_heap\&.h\&.
.SS "uint32_t* heap_state_t::heap_free_bitmap"
Pointer to the bitmap of free blocks, 0=free, 1=used 
.PP
Definition at line 50 of file bitmap_heap\&.h\&.
.SS "uint32_t* heap_state_t::heap_last_bitmap"
Pointer to the bitmap marking the last contiguous block in each allocation 
.PP
Definition at line 53 of file bitmap_heap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
