.TH "heap_tag" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
heap_tag \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBheap_tag\fP * \fBnext\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file nova_heap\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBheap_tag\fP* heap_tag::next"

.PP
Definition at line 19 of file nova_heap\&.c\&.
.SS "size_t heap_tag::size"

.PP
Definition at line 20 of file nova_heap\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
