.TH "ieee_double_shape_type" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee_double_shape_type \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <math_private\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBmsw\fP"
.br
.ti -1c
.RI "   uint32_t \fBlsw\fP"
.br
.ti -1c
.RI "} \fBparts\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBlsw\fP"
.br
.ti -1c
.RI "   uint32_t \fBmsw\fP"
.br
.ti -1c
.RI "} \fBparts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file math_private\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t ieee_double_shape_type::lsw"

.PP
Definition at line 26 of file math_private\&.h\&.
.SS "uint32_t ieee_double_shape_type::msw"

.PP
Definition at line 25 of file math_private\&.h\&.
.SS "struct { \&.\&.\&. }   ieee_double_shape_type::parts"

.SS "struct { \&.\&.\&. }   ieee_double_shape_type::parts"

.SS "double ieee_double_shape_type::value"

.PP
Definition at line 22 of file math_private\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
