.TH "kcall_heap_t" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kcall_heap_t \- 
.PP
Structure used for all of the heap operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <swi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBnmemb\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "void * \fBmemp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used for all of the heap operations\&. 
.PP
Definition at line 38 of file swi\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* kcall_heap_t::memp"
Size of allocation 
.PP
Definition at line 42 of file swi\&.h\&.
.SS "size_t kcall_heap_t::nmemb"

.PP
Definition at line 40 of file swi\&.h\&.
.SS "size_t kcall_heap_t::size"
Number of members (aka calloc) 
.PP
Definition at line 41 of file swi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
