.TH "src/kernel/kheap.c" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kernel/kheap.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/kernel/swi\&.h>\fP
.br
\fC#include <caribou/kernel/kheap\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBkheap_malloc\fP (void *arg)"
.br
.ti -1c
.RI "int \fBkheap_realloc\fP (void *arg)"
.br
.ti -1c
.RI "int \fBkheap_calloc\fP (void *arg)"
.br
.ti -1c
.RI "int \fBkheap_free\fP (void *arg)"
.br
.ti -1c
.RI "int \fBkheap_init\fP (void *arg)"
.br
.ti -1c
.RI "int \fBkheap_block_size\fP (void *arg)"
.br
.ti -1c
.RI "int \fBkheap_blocks_allocated\fP (void *arg)"
.br
.ti -1c
.RI "int \fBkheap_bytes_used\fP (void *arg)"
.br
.ti -1c
.RI "int \fBkheap_bytes_free\fP (void *arg)"
.br
.ti -1c
.RI "int \fBkheap_sizeof\fP (arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.PP
\fBAuthor:\fP
.RS 4
Mike Sharkey mike@pikeaero.com\&. 
.RE
.PP
\fBCopyright:\fP
.RS 4
© 2005-2013 by Pike Aerospace Research Corporation 
.PP
© 2014-2015 by Mike Sharkey
.RE
.PP
This file is part of CARIBOU RTOS CARIBOU RTOS is free software: you can redistribute it and/or modify it under the terms of the Beerware License Version 43\&. 'THE BEER-WARE LICENSE' (Revision 43): Mike Sharkey mike@pikeaero.com wrote this file\&. As long as you retain this notice you can do whatever you want with this stuff\&. If we meet some day, and you think this stuff is worth it, you can buy me a beer in return ~ Mike Sharkey 
.PP
Definition in file \fBkheap\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int kheap_block_size (void *arg)"

.PP
Definition at line 55 of file kheap\&.c\&.
.SS "int kheap_blocks_allocated (void *arg)"

.PP
Definition at line 62 of file kheap\&.c\&.
.SS "int kheap_bytes_free (void *arg)"

.PP
Definition at line 76 of file kheap\&.c\&.
.SS "int kheap_bytes_used (void *arg)"

.PP
Definition at line 69 of file kheap\&.c\&.
.SS "int kheap_calloc (void *arg)"

.PP
Definition at line 32 of file kheap\&.c\&.
.SS "int kheap_free (void *arg)"

.PP
Definition at line 39 of file kheap\&.c\&.
.SS "int kheap_init (void *arg)"

.PP
Definition at line 48 of file kheap\&.c\&.
.SS "int kheap_malloc (void *arg)"

.PP
Definition at line 18 of file kheap\&.c\&.
.SS "int kheap_realloc (void *arg)"

.PP
Definition at line 25 of file kheap\&.c\&.
.SS "int kheap_sizeof (arg)"

.PP
Definition at line 83 of file kheap\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
