.TH "include/caribou/lib/math_private.h" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/caribou/lib/math_private.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBieee_double_shape_type\fP"
.br
.ti -1c
.RI "union \fBieee_double_shape_type\fP"
.br
.ti -1c
.RI "union \fBieee_float_shape_type\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEXTRACT_WORDS\fP(ix0, ix1, d)"
.br
.ti -1c
.RI "#define \fBGET_HIGH_WORD\fP(i, d)"
.br
.ti -1c
.RI "#define \fBGET_LOW_WORD\fP(i, d)"
.br
.ti -1c
.RI "#define \fBINSERT_WORDS\fP(d, ix0, ix1)"
.br
.ti -1c
.RI "#define \fBSET_HIGH_WORD\fP(d, v)"
.br
.ti -1c
.RI "#define \fBSET_LOW_WORD\fP(d, v)"
.br
.ti -1c
.RI "#define \fBGET_FLOAT_WORD\fP(i, d)"
.br
.ti -1c
.RI "#define \fBSET_FLOAT_WORD\fP(d, i)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EXTRACT_WORDS(ix0, ix1, d)"
\fBValue:\fP
.PP
.nf
do {                              \
  ieee_double_shape_type ew_u;                  \
  ew_u\&.value = (d);                      \
  (ix0) = ew_u\&.parts\&.msw;                 \
  (ix1) = ew_u\&.parts\&.lsw;                 \
} while (0)
.fi
.PP
Definition at line 50 of file math_private\&.h\&.
.SS "#define GET_FLOAT_WORD(i, d)"
\fBValue:\fP
.PP
.nf
do {                             \
  ieee_float_shape_type gf_u;                   \
  gf_u\&.value = (d);                      \
  (i) = gf_u\&.word;                       \
} while (0)
.fi
.PP
Definition at line 117 of file math_private\&.h\&.
.SS "#define GET_HIGH_WORD(i, d)"
\fBValue:\fP
.PP
.nf
do {                             \
  ieee_double_shape_type gh_u;                  \
  gh_u\&.value = (d);                      \
  (i) = gh_u\&.parts\&.msw;                       \
} while (0)
.fi
.PP
Definition at line 60 of file math_private\&.h\&.
.SS "#define GET_LOW_WORD(i, d)"
\fBValue:\fP
.PP
.nf
do {                               \
  ieee_double_shape_type gl_u;                  \
  gl_u\&.value = (d);                      \
  (i) = gl_u\&.parts\&.lsw;                       \
} while (0)
.fi
.PP
Definition at line 69 of file math_private\&.h\&.
.SS "#define INSERT_WORDS(d, ix0, ix1)"
\fBValue:\fP
.PP
.nf
do {                                \
  ieee_double_shape_type iw_u;                  \
  iw_u\&.parts\&.msw = (ix0);                 \
  iw_u\&.parts\&.lsw = (ix1);                 \
  (d) = iw_u\&.value;                      \
} while (0)
.fi
.PP
Definition at line 78 of file math_private\&.h\&.
.SS "#define SET_FLOAT_WORD(d, i)"
\fBValue:\fP
.PP
.nf
do {                             \
  ieee_float_shape_type sf_u;                   \
  sf_u\&.word = (i);                       \
  (d) = sf_u\&.value;                      \
} while (0)
.fi
.PP
Definition at line 126 of file math_private\&.h\&.
.SS "#define SET_HIGH_WORD(d, v)"
\fBValue:\fP
.PP
.nf
do {                             \
  ieee_double_shape_type sh_u;                  \
  sh_u\&.value = (d);                      \
  sh_u\&.parts\&.msw = (v);                       \
  (d) = sh_u\&.value;                      \
} while (0)
.fi
.PP
Definition at line 88 of file math_private\&.h\&.
.SS "#define SET_LOW_WORD(d, v)"
\fBValue:\fP
.PP
.nf
do {                               \
  ieee_double_shape_type sl_u;                  \
  sl_u\&.value = (d);                      \
  sl_u\&.parts\&.lsw = (v);                       \
  (d) = sl_u\&.value;                      \
} while (0)
.fi
.PP
Definition at line 98 of file math_private\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
