.TH "include/caribou/lib/rand.h" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/caribou/lib/rand.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/kernel/types\&.h>\fP
.br
\fC#include <caribou/kernel/thread\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsrand\fP (uint32_t seed)"
.br
.ti -1c
.RI "uint32_t \fBrand\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t rand ()"

.PP
Definition at line 33 of file rand\&.c\&.
.SS "void srand (uint32_tseed)"

.PP
Definition at line 28 of file rand\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
