.TH "include/caribou/lib/spinlock.h" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/caribou/lib/spinlock.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/kernel/thread\&.h>\fP
.br
\fC#include <caribou/kernel/types\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBcaribou_thread_t\fP * \fBcaribou_spinlock_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcaribou_spinlock_init\fP (\fBcaribou_spinlock_t\fP *spinlock)"
.br
.RI "\fIinitialize a spinlock struct \fP"
.ti -1c
.RI "\fBbool\fP \fBcaribou_spinlock_lock\fP (\fBcaribou_spinlock_t\fP *spinlock)"
.br
.RI "\fItry to acquire lock - blocking \fP"
.ti -1c
.RI "\fBbool\fP \fBcaribou_spinlock_trylock\fP (\fBcaribou_spinlock_t\fP *spinlock)"
.br
.RI "\fItry to acquire a lock - non-blocking, return true of lock was acquired\&. \fP"
.ti -1c
.RI "\fBbool\fP \fBcaribou_spinlock_unlock\fP (\fBcaribou_spinlock_t\fP *spinlock)"
.br
.RI "\fIunlock a spinlock \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
.PP
\fBAuthor:\fP
.RS 4
Mike Sharkey mike@pikeaero.com\&. 
.RE
.PP
\fBCopyright:\fP
.RS 4
© 2005-2013 by Pike Aerospace Research Corporation 
.PP
© 2014-2015 by Mike Sharkey
.RE
.PP
This file is part of CARIBOU RTOS CARIBOU RTOS is free software: you can redistribute it and/or modify it under the terms of the Beerware License Version 43\&. 'THE BEER-WARE LICENSE' (Revision 43): Mike Sharkey mike@pikeaero.com wrote this file\&. As long as you retain this notice you can do whatever you want with this stuff\&. If we meet some day, and you think this stuff is worth it, you can buy me a beer in return ~ Mike Sharkey 
.PP
Definition in file \fBspinlock\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBcaribou_thread_t\fP* \fBcaribou_spinlock_t\fP"

.PP
Definition at line 26 of file spinlock\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void caribou_spinlock_init (\fBcaribou_spinlock_t\fP *spinlock)"

.PP
initialize a spinlock struct 
.PP
Definition at line 24 of file spinlock\&.c\&.
.SS "\fBbool\fP caribou_spinlock_lock (\fBcaribou_spinlock_t\fP *spinlock)"

.PP
try to acquire lock - blocking 
.PP
Definition at line 30 of file spinlock\&.c\&.
.SS "\fBbool\fP caribou_spinlock_trylock (\fBcaribou_spinlock_t\fP *spinlock)"

.PP
try to acquire a lock - non-blocking, return true of lock was acquired\&. 
.PP
Definition at line 38 of file spinlock\&.c\&.
.SS "\fBbool\fP caribou_spinlock_unlock (\fBcaribou_spinlock_t\fP *spinlock)"

.PP
unlock a spinlock 
.PP
Definition at line 50 of file spinlock\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
