.TH "include/caribou/kernel/swi.h" 3 "Thu Dec 29 2016" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/caribou/kernel/swi.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/kernel/types\&.h>\fP
.br
\fC#include <caribou/kernel/timer\&.h>\fP
.br
\fC#include <caribou/lib/errno\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBkcall_heap_t\fP"
.br
.RI "\fIStructure used for all of the heap operations\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBkcall_t\fP { \fBCARIBOU_KCALL_NOP\fP =0, \fBCARIBOU_KCALL_MALLOC\fP, \fBCARIBOU_KCALL_CALLOC\fP, \fBCARIBOU_KCALL_REALLOC\fP, \fBCARIBOU_KCALL_FREE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBkcall\fP (\fBkcall_t\fP fn, void *arg)"
.br
.RI "\fICall into the kernel from process thread space\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
.PP
\fBAuthor:\fP
.RS 4
Mike Sharkey mike@pikeaero.com\&. 
.RE
.PP
\fBCopyright:\fP
.RS 4
© 2014-2015 by Mike Sharkey
.RE
.PP
This file is part of CARIBOU RTOS CARIBOU RTOS is free software: you can redistribute it and/or modify it under the terms of the Beerware License Version 43\&. 'THE BEER-WARE LICENSE' (Revision 43): Mike Sharkey mike@pikeaero.com wrote this file\&. As long as you retain this notice you can do whatever you want with this stuff\&. If we meet some day, and you think this stuff is worth it, you can buy me a beer in return ~ Mike Sharkey 
.PP
Definition in file \fBswi\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBkcall_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICARIBOU_KCALL_NOP \fP\fP
.TP
\fB\fICARIBOU_KCALL_MALLOC \fP\fP
No Operation, test the kernel SWI 
.TP
\fB\fICARIBOU_KCALL_CALLOC \fP\fP
.TP
\fB\fICARIBOU_KCALL_REALLOC \fP\fP
.TP
\fB\fICARIBOU_KCALL_FREE \fP\fP
.PP
Definition at line 26 of file swi\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int kcall (\fBkcall_t\fPfn, void *arg)"

.PP
Call into the kernel from process thread space\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfn\fP Function code, indicates the ind of operation\&. 
.br
\fIarg\fP The argument pointer to data related to the kind of operation\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
0 upon success\&. -1 on errno\&. 
.RE
.PP

.PP
Definition at line 33 of file swi\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
