.TH "include/caribou/kernel/types.h" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/caribou/kernel/types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou_config\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNULL\fP   0"
.br
.ti -1c
.RI "#define \fBbool\fP   char"
.br
.ti -1c
.RI "#define \fBtrue\fP   (\fBbool\fP)1"
.br
.ti -1c
.RI "#define \fBfalse\fP   (\fBbool\fP)0"
.br
.ti -1c
.RI "#define \fBmax\fP(a, b)   (((a) > (b)) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fBmin\fP(a, b)   (((a) < (b)) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fBcaribou_lib_lock\fP()   \fBcaribou_thread_lock\fP()"
.br
.ti -1c
.RI "#define \fBcaribou_lib_unlock\fP()   \fBcaribou_thread_unlock\fP()"
.br
.ti -1c
.RI "#define \fBcaribou_lib_lock_restore\fP(n)   \fBcaribou_thread_unlock\fP()"
.br
.ti -1c
.RI "#define \fBASSERT\fP(x)"
.br
.ti -1c
.RI "#define \fBDEBUG_PRINTF\fP   \fBdebug_printf\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASSERT(x)"

.PP
Definition at line 84 of file types\&.h\&.
.SS "#define bool   char"

.PP
Definition at line 48 of file types\&.h\&.
.SS "#define caribou_lib_lock()   \fBcaribou_thread_lock\fP()"

.PP
Definition at line 73 of file types\&.h\&.
.SS "#define caribou_lib_lock_restore(n)   \fBcaribou_thread_unlock\fP()"

.PP
Definition at line 75 of file types\&.h\&.
.SS "#define caribou_lib_unlock()   \fBcaribou_thread_unlock\fP()"

.PP
Definition at line 74 of file types\&.h\&.
.SS "#define DEBUG_PRINTF   \fBdebug_printf\fP"

.PP
Definition at line 88 of file types\&.h\&.
.SS "#define false   (\fBbool\fP)0"

.PP
Definition at line 56 of file types\&.h\&.
.SS "#define max(a, b)   (((a) > (b)) ? (a) : (b))"

.PP
Definition at line 60 of file types\&.h\&.
.SS "#define min(a, b)   (((a) < (b)) ? (a) : (b))"

.PP
Definition at line 63 of file types\&.h\&.
.SS "#define NULL   0"

.PP
Definition at line 44 of file types\&.h\&.
.SS "#define true   (\fBbool\fP)1"

.PP
Definition at line 52 of file types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
