.TH "src/lib/errno.c" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib/errno.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/lib/errno\&.h>\fP
.br
\fC#include <caribou/kernel/thread\&.h>\fP
.br
\fC#include <caribou/lib/stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBperror\fP (char *s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBerrno_t\fP \fBerrno\fP =0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void perror (char *s)"

.PP
Definition at line 33 of file errno\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBerrno_t\fP errno =0"

.PP
Definition at line 22 of file errno\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
