.TH "src/lib/semaphore.c" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib/semaphore.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/kernel/interrupt\&.h>\fP
.br
\fC#include <caribou/lib/semaphore\&.h>\fP
.br
\fC#include <caribou/lib/errno\&.h>\fP
.br
\fC#include <caribou/lib/heap\&.h>\fP
.br
\fC#include <caribou/lib/string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcaribou_semaphore_t\fP * \fBcaribou_semaphore_new\fP (int depth, int count)"
.br
.RI "\fIAllocate and initialize a new semaphore on the heap\&. \fP"
.ti -1c
.RI "void \fBcaribou_semaphore_delete\fP (\fBcaribou_semaphore_t\fP *semaphore)"
.br
.ti -1c
.RI "\fBcaribou_semaphore_t\fP * \fBcaribou_semaphore_init\fP (\fBcaribou_semaphore_t\fP *semaphore, \fBcaribou_queue_t\fP *queue, int count)"
.br
.ti -1c
.RI "\fBcaribou_queue_t\fP * \fBcaribou_semaphore_queue\fP (\fBcaribou_semaphore_t\fP *semaphore)"
.br
.ti -1c
.RI "\fBbool\fP \fBcaribou_semaphore_signal\fP (\fBcaribou_semaphore_t\fP *semaphore)"
.br
.RI "\fIThis operation increases the semaphore counter, if the result is non-negative then a waiting thread is removed from the queue and resumed\&. Threads are removed from the queue in a FIFO manner\&. \fP"
.ti -1c
.RI "\fBbool\fP \fBcaribou_semaphore_wait\fP (\fBcaribou_semaphore_t\fP *semaphore, \fBcaribou_tick_t\fP timeout)"
.br
.RI "\fIThis operation decreases the semaphore counter, if the result is negative then the invoking thread is queued\&. \fP"
.ti -1c
.RI "\fBbool\fP \fBcaribou_semaphore_try_wait\fP (\fBcaribou_semaphore_t\fP *semaphore)"
.br
.RI "\fIThis operation decreases the semaphore counter, if the result is negative then the invoking thread is queued\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void caribou_semaphore_delete (\fBcaribou_semaphore_t\fP *semaphore)"

.PP
Definition at line 50 of file semaphore\&.c\&.
.SS "\fBcaribou_semaphore_t\fP* caribou_semaphore_init (\fBcaribou_semaphore_t\fP *semaphore, \fBcaribou_queue_t\fP *queue, intcount)"

.PP
Definition at line 66 of file semaphore\&.c\&.
.SS "\fBcaribou_semaphore_t\fP* caribou_semaphore_new (intdepth, intcount)"

.PP
Allocate and initialize a new semaphore on the heap\&. 
.PP
 
.PP
\fBParameters:\fP
.RS 4
\fIdepth\fP The depth of the thread queue (max number of waiting threads)\&. 
.br
\fIcount\fP The initial semaphore count\&. 
.RE
.PP

.PP
Definition at line 30 of file semaphore\&.c\&.
.SS "\fBcaribou_queue_t\fP* caribou_semaphore_queue (\fBcaribou_semaphore_t\fP *semaphore)"

.PP
Definition at line 76 of file semaphore\&.c\&.
.SS "\fBbool\fP caribou_semaphore_signal (\fBcaribou_semaphore_t\fP *semaphore)"

.PP
This operation increases the semaphore counter, if the result is non-negative then a waiting thread is removed from the queue and resumed\&. Threads are removed from the queue in a FIFO manner\&. 
.PP
 
.PP
\fBParameters:\fP
.RS 4
\fIsemaphore\fP The semaphore to operate on\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the semaphore was released\&. 
.RE
.PP

.PP
Definition at line 90 of file semaphore\&.c\&.
.SS "\fBbool\fP caribou_semaphore_try_wait (\fBcaribou_semaphore_t\fP *semaphore)"

.PP
This operation decreases the semaphore counter, if the result is negative then the invoking thread is queued\&. 
.PP
 
.PP
\fBParameters:\fP
.RS 4
\fIsemaphore\fP The semaphore to operate on\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
true of the semaphore was released\&. 
.RE
.PP

.PP
Definition at line 132 of file semaphore\&.c\&.
.SS "\fBbool\fP caribou_semaphore_wait (\fBcaribou_semaphore_t\fP *semaphore, \fBcaribou_tick_t\fPtimeout)"

.PP
This operation decreases the semaphore counter, if the result is negative then the invoking thread is queued\&. 
.PP
 
.PP
\fBParameters:\fP
.RS 4
\fIsemaphore\fP The semaphore to operate on\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
true of the semaphore was released\&. 
.RE
.PP

.PP
Definition at line 117 of file semaphore\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
