.TH "_caribou_timer_t" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_caribou_timer_t \- 
.PP
The caribou_timer_t structure defines the data structure used by CARIBOU to maintain timers and sleep periods\&. The structure elements should not me manipulated by the application program, and are subject to change in future releases\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timer\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fB_caribou_timer_t\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fB_caribou_timer_t\fP * \fBnext\fP"
.br
.RI "\fIprev in chain \fP"
.ti -1c
.RI "\fBcaribou_timer_callback_fn\fP * \fBtimerfn\fP"
.br
.RI "\fInext in chain \fP"
.ti -1c
.RI "void * \fBfnarg\fP"
.br
.RI "\fItimer callback function \fP"
.ti -1c
.RI "uint32_t \fBticks\fP"
.br
.RI "\fItimer callback argument \fP"
.ti -1c
.RI "uint32_t \fBreloadticks\fP"
.br
.RI "\fIthe remaining ticks \fP"
.ti -1c
.RI "uint8_t \fBflags\fP"
.br
.RI "\fIthe reload value \fP"
.in -1c
.SH "Detailed Description"
.PP 
The caribou_timer_t structure defines the data structure used by CARIBOU to maintain timers and sleep periods\&. The structure elements should not me manipulated by the application program, and are subject to change in future releases\&. 
.PP
Definition at line 57 of file timer\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t _caribou_timer_t::flags"

.PP
the reload value 
.PP
Definition at line 65 of file timer\&.h\&.
.SS "void* _caribou_timer_t::fnarg"

.PP
timer callback function 
.PP
Definition at line 62 of file timer\&.h\&.
.SS "struct \fB_caribou_timer_t\fP* _caribou_timer_t::next"

.PP
prev in chain 
.PP
Definition at line 60 of file timer\&.h\&.
.SS "struct \fB_caribou_timer_t\fP* _caribou_timer_t::prev"

.PP
Definition at line 59 of file timer\&.h\&.
.SS "uint32_t _caribou_timer_t::reloadticks"

.PP
the remaining ticks 
.PP
Definition at line 64 of file timer\&.h\&.
.SS "uint32_t _caribou_timer_t::ticks"

.PP
timer callback argument 
.PP
Definition at line 63 of file timer\&.h\&.
.SS "\fBcaribou_timer_callback_fn\fP* _caribou_timer_t::timerfn"

.PP
next in chain 
.PP
Definition at line 61 of file timer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
