.TH "src/dev/adc.c" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dev/adc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/dev/adc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcaribou_adc_start\fP (\fBcaribou_adc_t\fP *adc)"
.br
.ti -1c
.RI "int \fBcaribou_adc_ready\fP (\fBcaribou_adc_t\fP *adc)"
.br
.ti -1c
.RI "chip_adc_value_t \fBcaribou_adc_value\fP (\fBcaribou_adc_t\fP *adc)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int caribou_adc_ready (\fBcaribou_adc_t\fP *adc)"

.PP
Definition at line 24 of file adc\&.c\&.
.SS "int caribou_adc_start (\fBcaribou_adc_t\fP *adc)"

.PP
Definition at line 19 of file adc\&.c\&.
.SS "chip_adc_value_t caribou_adc_value (\fBcaribou_adc_t\fP *adc)"

.PP
Definition at line 29 of file adc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
