.TH "caribou_interrupt_handler_s" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
caribou_interrupt_handler_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcaribou_isr_t\fP \fBisr\fP"
.br
.ti -1c
.RI "void * \fBarg\fP"
.br
.ti -1c
.RI "struct 
.br
\fBcaribou_interrupt_handler_s\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file interrupt\&.c\&.
.SH "Field Documentation"
.PP 
.SS "void* caribou_interrupt_handler_s::arg"

.PP
Definition at line 23 of file interrupt\&.c\&.
.SS "\fBcaribou_isr_t\fP caribou_interrupt_handler_s::isr"

.PP
Definition at line 22 of file interrupt\&.c\&.
.SS "struct \fBcaribou_interrupt_handler_s\fP* caribou_interrupt_handler_s::next"

.PP
Definition at line 24 of file interrupt\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
