.TH "caribou_gpio_t" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
caribou_gpio_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gpio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "chip_gpio_port_t \fBport\fP"
.br
.ti -1c
.RI "chip_gpio_pinmask_t \fBpinmask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file gpio\&.h\&.
.SH "Field Documentation"
.PP 
.SS "chip_gpio_pinmask_t caribou_gpio_t::pinmask"

.PP
Definition at line 35 of file gpio\&.h\&.
.SS "chip_gpio_port_t caribou_gpio_t::port"

.PP
Definition at line 34 of file gpio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
