.TH "caribou_i2c_t" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
caribou_i2c_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "chip_i2c_port_t \fBport\fP"
.br
.ti -1c
.RI "uint8_t \fBdevice_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file i2c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t caribou_i2c_t::device_address"

.PP
Definition at line 35 of file i2c\&.h\&.
.SS "chip_i2c_port_t caribou_i2c_t::port"

.PP
Definition at line 34 of file i2c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
