.TH "caribou_adc_t" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
caribou_adc_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <adc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "chip_adc_port_t \fBport\fP"
.br
.ti -1c
.RI "chip_adc_channel_t \fBchannel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file adc\&.h\&.
.SH "Field Documentation"
.PP 
.SS "chip_adc_channel_t caribou_adc_t::channel"

.PP
Definition at line 35 of file adc\&.h\&.
.SS "chip_adc_port_t caribou_adc_t::port"

.PP
Definition at line 34 of file adc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
