.TH "include/caribou/lib/errno.h" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/caribou/lib/errno.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEDOM\fP   0x01"
.br
.ti -1c
.RI "#define \fBEILSEQ\fP   0x02"
.br
.ti -1c
.RI "#define \fBERANGE\fP   0x03"
.br
.ti -1c
.RI "#define \fBEHEAP\fP   0x04"
.br
.ti -1c
.RI "#define \fBENOMEM\fP   0x05"
.br
.RI "\fINo memory available \\
.PP
\fB\fP  - no memory can be allocated by a function in the library\&. Note that \fBmalloc\fP, \fBcalloc\fP, and \fBrealloc\fP do not set \fBerrno\fP to \fBENOMEM\fP on failure, but other library routines (such as \fBduplocale\fP) may set \fBerrno\fP to \fBENOMEM\fP when memory allocation fails\&. \fP"
.ti -1c
.RI "#define \fBEINVAL\fP   0x06"
.br
.RI "\fIInvalid argument \\
.PP
\fB\fP  - An argument was invalid, or a combination of arguments was invalid\&. \fP"
.ti -1c
.RI "#define \fBerrno\fP   (*\fB__errno\fP())"
.br
.ti -1c
.RI "#define \fBEOKAY\fP   0  /* No error */"
.br
.ti -1c
.RI "#define \fBEPERM\fP   1	/* Operation not permitted */"
.br
.ti -1c
.RI "#define \fBENOENT\fP   2	/* No such file or directory */"
.br
.ti -1c
.RI "#define \fBESRCH\fP   3	/* No such process */"
.br
.ti -1c
.RI "#define \fBEINTR\fP   4	/* Interrupted system call */"
.br
.ti -1c
.RI "#define \fBEIO\fP   5	/* I/O error */"
.br
.ti -1c
.RI "#define \fBENXIO\fP   6	/* No such device or address */"
.br
.ti -1c
.RI "#define \fBE2BIG\fP   7	/* Argument list too long */"
.br
.ti -1c
.RI "#define \fBENOEXEC\fP   8	/* Exec format error */"
.br
.ti -1c
.RI "#define \fBEBADF\fP   9	/* Bad file number */"
.br
.ti -1c
.RI "#define \fBECHILD\fP   10	/* No child processes */"
.br
.ti -1c
.RI "#define \fBEAGAIN\fP   11	/* Try again */"
.br
.ti -1c
.RI "#define \fBENOMEM\fP   12	/* Out of memory */"
.br
.RI "\fINo memory available \\
.PP
\fB\fP  - no memory can be allocated by a function in the library\&. Note that \fBmalloc\fP, \fBcalloc\fP, and \fBrealloc\fP do not set \fBerrno\fP to \fBENOMEM\fP on failure, but other library routines (such as \fBduplocale\fP) may set \fBerrno\fP to \fBENOMEM\fP when memory allocation fails\&. \fP"
.ti -1c
.RI "#define \fBEACCES\fP   13	/* Permission denied */"
.br
.ti -1c
.RI "#define \fBEFAULT\fP   14	/* Bad address */"
.br
.ti -1c
.RI "#define \fBENOTBLK\fP   15	/* Block device required */"
.br
.ti -1c
.RI "#define \fBEBUSY\fP   16	/* Device or resource busy */"
.br
.ti -1c
.RI "#define \fBEEXIST\fP   17	/* File exists */"
.br
.ti -1c
.RI "#define \fBEXDEV\fP   18	/* Cross-device link */"
.br
.ti -1c
.RI "#define \fBENODEV\fP   19	/* No such device */"
.br
.ti -1c
.RI "#define \fBENOTDIR\fP   20	/* Not a directory */"
.br
.ti -1c
.RI "#define \fBEISDIR\fP   21	/* Is a directory */"
.br
.ti -1c
.RI "#define \fBEINVAL\fP   22	/* Invalid argument */"
.br
.RI "\fIInvalid argument \\
.PP
\fB\fP  - An argument was invalid, or a combination of arguments was invalid\&. \fP"
.ti -1c
.RI "#define \fBENFILE\fP   23	/* File table overflow */"
.br
.ti -1c
.RI "#define \fBEMFILE\fP   24	/* Too many open files */"
.br
.ti -1c
.RI "#define \fBENOTTY\fP   25	/* Not a typewriter */"
.br
.ti -1c
.RI "#define \fBETXTBSY\fP   26	/* Text file busy */"
.br
.ti -1c
.RI "#define \fBEFBIG\fP   27	/* File too large */"
.br
.ti -1c
.RI "#define \fBENOSPC\fP   28	/* No space left on device */"
.br
.ti -1c
.RI "#define \fBESPIPE\fP   29	/* Illegal seek */"
.br
.ti -1c
.RI "#define \fBEROFS\fP   30	/* Read-only file system */"
.br
.ti -1c
.RI "#define \fBEMLINK\fP   31	/* Too many links */"
.br
.ti -1c
.RI "#define \fBEPIPE\fP   32	/* Broken pipe */"
.br
.ti -1c
.RI "#define \fBEDOM\fP   33	/* Math argument out of domain of func */"
.br
.ti -1c
.RI "#define \fBERANGE\fP   34	/* Math result not representable */"
.br
.ti -1c
.RI "#define \fBEDEADLK\fP   35	/* Resource deadlock would occur */"
.br
.ti -1c
.RI "#define \fBENAMETOOLONG\fP   36	/* File name too long */"
.br
.ti -1c
.RI "#define \fBENOLCK\fP   37	/* No record locks available */"
.br
.ti -1c
.RI "#define \fBENOSYS\fP   38	/* Function not implemented */"
.br
.ti -1c
.RI "#define \fBENOTEMPTY\fP   39	/* Directory not empty */"
.br
.ti -1c
.RI "#define \fBELOOP\fP   40	/* Too many symbolic links encountered */"
.br
.ti -1c
.RI "#define \fBEWOULDBLOCK\fP   \fBEAGAIN\fP	/* Operation would block */"
.br
.ti -1c
.RI "#define \fBENOMSG\fP   42	/* No message of desired type */"
.br
.ti -1c
.RI "#define \fBEIDRM\fP   43	/* Identifier removed */"
.br
.ti -1c
.RI "#define \fBECHRNG\fP   44	/* Channel number out of range */"
.br
.ti -1c
.RI "#define \fBEL2NSYNC\fP   45	/* Level 2 not synchronized */"
.br
.ti -1c
.RI "#define \fBEL3HLT\fP   46	/* Level 3 halted */"
.br
.ti -1c
.RI "#define \fBEL3RST\fP   47	/* Level 3 \fBreset\fP */"
.br
.ti -1c
.RI "#define \fBELNRNG\fP   48	/* Link number out of range */"
.br
.ti -1c
.RI "#define \fBEUNATCH\fP   49	/* Protocol driver not attached */"
.br
.ti -1c
.RI "#define \fBENOCSI\fP   50	/* No CSI structure available */"
.br
.ti -1c
.RI "#define \fBEL2HLT\fP   51	/* Level 2 halted */"
.br
.ti -1c
.RI "#define \fBEBADE\fP   52	/* Invalid exchange */"
.br
.ti -1c
.RI "#define \fBEBADR\fP   53	/* Invalid request descriptor */"
.br
.ti -1c
.RI "#define \fBEXFULL\fP   54	/* Exchange full */"
.br
.ti -1c
.RI "#define \fBENOANO\fP   55	/* No anode */"
.br
.ti -1c
.RI "#define \fBEBADRQC\fP   56	/* Invalid request code */"
.br
.ti -1c
.RI "#define \fBEBADSLT\fP   57	/* Invalid slot */"
.br
.ti -1c
.RI "#define \fBEDEADLOCK\fP   \fBEDEADLK\fP"
.br
.ti -1c
.RI "#define \fBEBFONT\fP   59	/* Bad font file format */"
.br
.ti -1c
.RI "#define \fBENOSTR\fP   60	/* Device not a stream */"
.br
.ti -1c
.RI "#define \fBENODATA\fP   61	/* No data available */"
.br
.ti -1c
.RI "#define \fBETIME\fP   62	/* Timer expired */"
.br
.ti -1c
.RI "#define \fBENOSR\fP   63	/* Out of streams resources */"
.br
.ti -1c
.RI "#define \fBENONET\fP   64	/* Machine is not on the network */"
.br
.ti -1c
.RI "#define \fBENOPKG\fP   65	/* Package not installed */"
.br
.ti -1c
.RI "#define \fBEREMOTE\fP   66	/* Object is remote */"
.br
.ti -1c
.RI "#define \fBENOLINK\fP   67	/* Link has been severed */"
.br
.ti -1c
.RI "#define \fBEADV\fP   68	/* Advertise error */"
.br
.ti -1c
.RI "#define \fBESRMNT\fP   69	/* Srmount error */"
.br
.ti -1c
.RI "#define \fBECOMM\fP   70	/* Communication error on send */"
.br
.ti -1c
.RI "#define \fBEPROTO\fP   71	/* Protocol error */"
.br
.ti -1c
.RI "#define \fBEMULTIHOP\fP   72	/* Multihop attempted */"
.br
.ti -1c
.RI "#define \fBEDOTDOT\fP   73	/* RFS specific error */"
.br
.ti -1c
.RI "#define \fBEBADMSG\fP   74	/* Not a data message */"
.br
.ti -1c
.RI "#define \fBEOVERFLOW\fP   75	/* Value too large for defined data type */"
.br
.ti -1c
.RI "#define \fBENOTUNIQ\fP   76	/* Name not unique on network */"
.br
.ti -1c
.RI "#define \fBEBADFD\fP   77	/* File descriptor in bad state */"
.br
.ti -1c
.RI "#define \fBEREMCHG\fP   78	/* Remote address changed */"
.br
.ti -1c
.RI "#define \fBELIBACC\fP   79	/* Can not access a needed shared library */"
.br
.ti -1c
.RI "#define \fBELIBBAD\fP   80	/* Accessing a corrupted shared library */"
.br
.ti -1c
.RI "#define \fBELIBSCN\fP   81	/* \&.lib section in a\&.out corrupted */"
.br
.ti -1c
.RI "#define \fBELIBMAX\fP   82	/* Attempting to link in too many shared libraries */"
.br
.ti -1c
.RI "#define \fBELIBEXEC\fP   83	/* Cannot exec a shared library directly */"
.br
.ti -1c
.RI "#define \fBEILSEQ\fP   84	/* Illegal byte sequence */"
.br
.ti -1c
.RI "#define \fBERESTART\fP   85	/* Interrupted system call should be restarted */"
.br
.ti -1c
.RI "#define \fBESTRPIPE\fP   86	/* Streams pipe error */"
.br
.ti -1c
.RI "#define \fBEUSERS\fP   87	/* Too many users */"
.br
.ti -1c
.RI "#define \fBENOTSOCK\fP   88	/* Socket operation on non-socket */"
.br
.ti -1c
.RI "#define \fBEDESTADDRREQ\fP   89	/* Destination address required */"
.br
.ti -1c
.RI "#define \fBEMSGSIZE\fP   90	/* Message too long */"
.br
.ti -1c
.RI "#define \fBEPROTOTYPE\fP   91	/* Protocol wrong type for socket */"
.br
.ti -1c
.RI "#define \fBENOPROTOOPT\fP   92	/* Protocol not available */"
.br
.ti -1c
.RI "#define \fBEPROTONOSUPPORT\fP   93	/* Protocol not supported */"
.br
.ti -1c
.RI "#define \fBESOCKTNOSUPPORT\fP   94	/* Socket type not supported */"
.br
.ti -1c
.RI "#define \fBEOPNOTSUPP\fP   95	/* Operation not supported on transport endpoint */"
.br
.ti -1c
.RI "#define \fBEPFNOSUPPORT\fP   96	/* Protocol family not supported */"
.br
.ti -1c
.RI "#define \fBEAFNOSUPPORT\fP   97	/* Address family not supported by protocol */"
.br
.ti -1c
.RI "#define \fBEADDRINUSE\fP   98	/* Address already in use */"
.br
.ti -1c
.RI "#define \fBEADDRNOTAVAIL\fP   99	/* Cannot assign requested address */"
.br
.ti -1c
.RI "#define \fBENETDOWN\fP   100	/* Network is down */"
.br
.ti -1c
.RI "#define \fBENETUNREACH\fP   101	/* Network is unreachable */"
.br
.ti -1c
.RI "#define \fBENETRESET\fP   102	/* Network dropped connection because of \fBreset\fP */"
.br
.ti -1c
.RI "#define \fBECONNABORTED\fP   103	/* Software caused connection abort */"
.br
.ti -1c
.RI "#define \fBECONNRESET\fP   104	/* Connection \fBreset\fP by peer */"
.br
.ti -1c
.RI "#define \fBENOBUFS\fP   105	/* No buffer space available */"
.br
.ti -1c
.RI "#define \fBEISCONN\fP   106	/* Transport endpoint is already connected */"
.br
.ti -1c
.RI "#define \fBENOTCONN\fP   107	/* Transport endpoint is not connected */"
.br
.ti -1c
.RI "#define \fBESHUTDOWN\fP   108	/* Cannot send after transport endpoint shutdown */"
.br
.ti -1c
.RI "#define \fBETOOMANYREFS\fP   109	/* Too many references: cannot splice */"
.br
.ti -1c
.RI "#define \fBETIMEDOUT\fP   110	/* Connection timed out */"
.br
.ti -1c
.RI "#define \fBECONNREFUSED\fP   111	/* Connection refused */"
.br
.ti -1c
.RI "#define \fBEHOSTDOWN\fP   112	/* Host is down */"
.br
.ti -1c
.RI "#define \fBEHOSTUNREACH\fP   113	/* No route to host */"
.br
.ti -1c
.RI "#define \fBEALREADY\fP   114	/* Operation already in progress */"
.br
.ti -1c
.RI "#define \fBEINPROGRESS\fP   115	/* Operation now in progress */"
.br
.ti -1c
.RI "#define \fBESTALE\fP   116	/* Stale NFS file handle */"
.br
.ti -1c
.RI "#define \fBEUCLEAN\fP   117	/* Structure needs cleaning */"
.br
.ti -1c
.RI "#define \fBENOTNAM\fP   118	/* Not a XENIX named type file */"
.br
.ti -1c
.RI "#define \fBENAVAIL\fP   119	/* No XENIX semaphores available */"
.br
.ti -1c
.RI "#define \fBEISNAM\fP   120	/* Is a named type file */"
.br
.ti -1c
.RI "#define \fBEREMOTEIO\fP   121	/* Remote I/O error */"
.br
.ti -1c
.RI "#define \fBEDQUOT\fP   122	/* Quota exceeded */"
.br
.ti -1c
.RI "#define \fBENOMEDIUM\fP   123	/* No medium found */"
.br
.ti -1c
.RI "#define \fBEMEDIUMTYPE\fP   124	/* Wrong medium type */"
.br
.ti -1c
.RI "#define \fBECANCELED\fP   125	/* Operation Canceled */"
.br
.ti -1c
.RI "#define \fBENOKEY\fP   126	/* Required key not available */"
.br
.ti -1c
.RI "#define \fBEKEYEXPIRED\fP   127	/* Key has expired */"
.br
.ti -1c
.RI "#define \fBEKEYREVOKED\fP   128	/* Key has been revoked */"
.br
.ti -1c
.RI "#define \fBEKEYREJECTED\fP   129	/* Key was rejected by service */"
.br
.ti -1c
.RI "#define \fBEOWNERDEAD\fP   130	/* Owner died */"
.br
.ti -1c
.RI "#define \fBENOTRECOVERABLE\fP   131	/* State not recoverable */"
.br
.ti -1c
.RI "#define \fBERFKILL\fP   132	/* Operation not possible due to RF-kill */"
.br
.ti -1c
.RI "#define \fBEHWPOISON\fP   133	/* Memory page has hardware error */"
.br
.ti -1c
.RI "#define \fBerrno\fP   \fB__errno\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBerrno_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "volatile int * \fB__errno\fP (void)"
.br
.ti -1c
.RI "void \fBperror\fP (char *s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBerrno_t\fP \fB__errno\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define E2BIG   7	/* Argument list too long */"

.PP
Definition at line 131 of file errno\&.h\&.
.SS "#define EACCES   13	/* Permission denied */"

.PP
Definition at line 137 of file errno\&.h\&.
.SS "#define EADDRINUSE   98	/* Address already in use */"

.PP
Definition at line 224 of file errno\&.h\&.
.SS "#define EADDRNOTAVAIL   99	/* Cannot assign requested address */"

.PP
Definition at line 225 of file errno\&.h\&.
.SS "#define EADV   68	/* Advertise error */"

.PP
Definition at line 194 of file errno\&.h\&.
.SS "#define EAFNOSUPPORT   97	/* Address family not supported by protocol */"

.PP
Definition at line 223 of file errno\&.h\&.
.SS "#define EAGAIN   11	/* Try again */"

.PP
Definition at line 135 of file errno\&.h\&.
.SS "#define EALREADY   114	/* Operation already in progress */"

.PP
Definition at line 240 of file errno\&.h\&.
.SS "#define EBADE   52	/* Invalid exchange */"

.PP
Definition at line 176 of file errno\&.h\&.
.SS "#define EBADF   9	/* Bad file number */"

.PP
Definition at line 133 of file errno\&.h\&.
.SS "#define EBADFD   77	/* File descriptor in bad state */"

.PP
Definition at line 203 of file errno\&.h\&.
.SS "#define EBADMSG   74	/* Not a data message */"

.PP
Definition at line 200 of file errno\&.h\&.
.SS "#define EBADR   53	/* Invalid request descriptor */"

.PP
Definition at line 177 of file errno\&.h\&.
.SS "#define EBADRQC   56	/* Invalid request code */"

.PP
Definition at line 180 of file errno\&.h\&.
.SS "#define EBADSLT   57	/* Invalid slot */"

.PP
Definition at line 181 of file errno\&.h\&.
.SS "#define EBFONT   59	/* Bad font file format */"

.PP
Definition at line 185 of file errno\&.h\&.
.SS "#define EBUSY   16	/* Device or resource busy */"

.PP
Definition at line 140 of file errno\&.h\&.
.SS "#define ECANCELED   125	/* Operation Canceled */"

.PP
Definition at line 252 of file errno\&.h\&.
.SS "#define ECHILD   10	/* No child processes */"

.PP
Definition at line 134 of file errno\&.h\&.
.SS "#define ECHRNG   44	/* Channel number out of range */"

.PP
Definition at line 168 of file errno\&.h\&.
.SS "#define ECOMM   70	/* Communication error on send */"

.PP
Definition at line 196 of file errno\&.h\&.
.SS "#define ECONNABORTED   103	/* Software caused connection abort */"

.PP
Definition at line 229 of file errno\&.h\&.
.SS "#define ECONNREFUSED   111	/* Connection refused */"

.PP
Definition at line 237 of file errno\&.h\&.
.SS "#define ECONNRESET   104	/* Connection \fBreset\fP by peer */"

.PP
Definition at line 230 of file errno\&.h\&.
.SS "#define EDEADLK   35	/* Resource deadlock would occur */"

.PP
Definition at line 159 of file errno\&.h\&.
.SS "#define EDEADLOCK   \fBEDEADLK\fP"

.PP
Definition at line 183 of file errno\&.h\&.
.SS "#define EDESTADDRREQ   89	/* Destination address required */"

.PP
Definition at line 215 of file errno\&.h\&.
.SS "#define EDOM   0x01"

.PP
Definition at line 157 of file errno\&.h\&.
.SS "#define EDOM   33	/* Math argument out of domain of func */"

.PP
Definition at line 157 of file errno\&.h\&.
.SS "#define EDOTDOT   73	/* RFS specific error */"

.PP
Definition at line 199 of file errno\&.h\&.
.SS "#define EDQUOT   122	/* Quota exceeded */"

.PP
Definition at line 248 of file errno\&.h\&.
.SS "#define EEXIST   17	/* File exists */"

.PP
Definition at line 141 of file errno\&.h\&.
.SS "#define EFAULT   14	/* Bad address */"

.PP
Definition at line 138 of file errno\&.h\&.
.SS "#define EFBIG   27	/* File too large */"

.PP
Definition at line 151 of file errno\&.h\&.
.SS "#define EHEAP   0x04"

.PP
Definition at line 41 of file errno\&.h\&.
.SS "#define EHOSTDOWN   112	/* Host is down */"

.PP
Definition at line 238 of file errno\&.h\&.
.SS "#define EHOSTUNREACH   113	/* No route to host */"

.PP
Definition at line 239 of file errno\&.h\&.
.SS "#define EHWPOISON   133	/* Memory page has hardware error */"

.PP
Definition at line 264 of file errno\&.h\&.
.SS "#define EIDRM   43	/* Identifier removed */"

.PP
Definition at line 167 of file errno\&.h\&.
.SS "#define EILSEQ   0x02"

.PP
Definition at line 210 of file errno\&.h\&.
.SS "#define EILSEQ   84	/* Illegal byte sequence */"

.PP
Definition at line 210 of file errno\&.h\&.
.SS "#define EINPROGRESS   115	/* Operation now in progress */"

.PP
Definition at line 241 of file errno\&.h\&.
.SS "#define EINTR   4	/* Interrupted system call */"

.PP
Definition at line 128 of file errno\&.h\&.
.SS "#define EINVAL   0x06"

.PP
Invalid argument \\
.PP
\fB\fP  - An argument was invalid, or a combination of arguments was invalid\&. 
.PP
Definition at line 146 of file errno\&.h\&.
.SS "#define EINVAL   22	/* Invalid argument */"

.PP
Invalid argument \\
.PP
\fB\fP  - An argument was invalid, or a combination of arguments was invalid\&. 
.PP
Definition at line 146 of file errno\&.h\&.
.SS "#define EIO   5	/* I/O error */"

.PP
Definition at line 129 of file errno\&.h\&.
.SS "#define EISCONN   106	/* Transport endpoint is already connected */"

.PP
Definition at line 232 of file errno\&.h\&.
.SS "#define EISDIR   21	/* Is a directory */"

.PP
Definition at line 145 of file errno\&.h\&.
.SS "#define EISNAM   120	/* Is a named type file */"

.PP
Definition at line 246 of file errno\&.h\&.
.SS "#define EKEYEXPIRED   127	/* Key has expired */"

.PP
Definition at line 254 of file errno\&.h\&.
.SS "#define EKEYREJECTED   129	/* Key was rejected by service */"

.PP
Definition at line 256 of file errno\&.h\&.
.SS "#define EKEYREVOKED   128	/* Key has been revoked */"

.PP
Definition at line 255 of file errno\&.h\&.
.SS "#define EL2HLT   51	/* Level 2 halted */"

.PP
Definition at line 175 of file errno\&.h\&.
.SS "#define EL2NSYNC   45	/* Level 2 not synchronized */"

.PP
Definition at line 169 of file errno\&.h\&.
.SS "#define EL3HLT   46	/* Level 3 halted */"

.PP
Definition at line 170 of file errno\&.h\&.
.SS "#define EL3RST   47	/* Level 3 \fBreset\fP */"

.PP
Definition at line 171 of file errno\&.h\&.
.SS "#define ELIBACC   79	/* Can not access a needed shared library */"

.PP
Definition at line 205 of file errno\&.h\&.
.SS "#define ELIBBAD   80	/* Accessing a corrupted shared library */"

.PP
Definition at line 206 of file errno\&.h\&.
.SS "#define ELIBEXEC   83	/* Cannot exec a shared library directly */"

.PP
Definition at line 209 of file errno\&.h\&.
.SS "#define ELIBMAX   82	/* Attempting to link in too many shared libraries */"

.PP
Definition at line 208 of file errno\&.h\&.
.SS "#define ELIBSCN   81	/* \&.lib section in a\&.out corrupted */"

.PP
Definition at line 207 of file errno\&.h\&.
.SS "#define ELNRNG   48	/* Link number out of range */"

.PP
Definition at line 172 of file errno\&.h\&.
.SS "#define ELOOP   40	/* Too many symbolic links encountered */"

.PP
Definition at line 164 of file errno\&.h\&.
.SS "#define EMEDIUMTYPE   124	/* Wrong medium type */"

.PP
Definition at line 251 of file errno\&.h\&.
.SS "#define EMFILE   24	/* Too many open files */"

.PP
Definition at line 148 of file errno\&.h\&.
.SS "#define EMLINK   31	/* Too many links */"

.PP
Definition at line 155 of file errno\&.h\&.
.SS "#define EMSGSIZE   90	/* Message too long */"

.PP
Definition at line 216 of file errno\&.h\&.
.SS "#define EMULTIHOP   72	/* Multihop attempted */"

.PP
Definition at line 198 of file errno\&.h\&.
.SS "#define ENAMETOOLONG   36	/* File name too long */"

.PP
Definition at line 160 of file errno\&.h\&.
.SS "#define ENAVAIL   119	/* No XENIX semaphores available */"

.PP
Definition at line 245 of file errno\&.h\&.
.SS "#define ENETDOWN   100	/* Network is down */"

.PP
Definition at line 226 of file errno\&.h\&.
.SS "#define ENETRESET   102	/* Network dropped connection because of \fBreset\fP */"

.PP
Definition at line 228 of file errno\&.h\&.
.SS "#define ENETUNREACH   101	/* Network is unreachable */"

.PP
Definition at line 227 of file errno\&.h\&.
.SS "#define ENFILE   23	/* File table overflow */"

.PP
Definition at line 147 of file errno\&.h\&.
.SS "#define ENOANO   55	/* No anode */"

.PP
Definition at line 179 of file errno\&.h\&.
.SS "#define ENOBUFS   105	/* No buffer space available */"

.PP
Definition at line 231 of file errno\&.h\&.
.SS "#define ENOCSI   50	/* No CSI structure available */"

.PP
Definition at line 174 of file errno\&.h\&.
.SS "#define ENODATA   61	/* No data available */"

.PP
Definition at line 187 of file errno\&.h\&.
.SS "#define ENODEV   19	/* No such device */"

.PP
Definition at line 143 of file errno\&.h\&.
.SS "#define ENOENT   2	/* No such file or directory */"

.PP
Definition at line 126 of file errno\&.h\&.
.SS "#define ENOEXEC   8	/* Exec format error */"

.PP
Definition at line 132 of file errno\&.h\&.
.SS "#define ENOKEY   126	/* Required key not available */"

.PP
Definition at line 253 of file errno\&.h\&.
.SS "#define ENOLCK   37	/* No record locks available */"

.PP
Definition at line 161 of file errno\&.h\&.
.SS "#define ENOLINK   67	/* Link has been severed */"

.PP
Definition at line 193 of file errno\&.h\&.
.SS "#define ENOMEDIUM   123	/* No medium found */"

.PP
Definition at line 250 of file errno\&.h\&.
.SS "#define ENOMEM   0x05"

.PP
No memory available \\
.PP
\fB\fP  - no memory can be allocated by a function in the library\&. Note that \fBmalloc\fP, \fBcalloc\fP, and \fBrealloc\fP do not set \fBerrno\fP to \fBENOMEM\fP on failure, but other library routines (such as \fBduplocale\fP) may set \fBerrno\fP to \fBENOMEM\fP when memory allocation fails\&. 
.PP
Definition at line 136 of file errno\&.h\&.
.SS "#define ENOMEM   12	/* Out of memory */"

.PP
No memory available \\
.PP
\fB\fP  - no memory can be allocated by a function in the library\&. Note that \fBmalloc\fP, \fBcalloc\fP, and \fBrealloc\fP do not set \fBerrno\fP to \fBENOMEM\fP on failure, but other library routines (such as \fBduplocale\fP) may set \fBerrno\fP to \fBENOMEM\fP when memory allocation fails\&. 
.PP
Definition at line 136 of file errno\&.h\&.
.SS "#define ENOMSG   42	/* No message of desired type */"

.PP
Definition at line 166 of file errno\&.h\&.
.SS "#define ENONET   64	/* Machine is not on the network */"

.PP
Definition at line 190 of file errno\&.h\&.
.SS "#define ENOPKG   65	/* Package not installed */"

.PP
Definition at line 191 of file errno\&.h\&.
.SS "#define ENOPROTOOPT   92	/* Protocol not available */"

.PP
Definition at line 218 of file errno\&.h\&.
.SS "#define ENOSPC   28	/* No space left on device */"

.PP
Definition at line 152 of file errno\&.h\&.
.SS "#define ENOSR   63	/* Out of streams resources */"

.PP
Definition at line 189 of file errno\&.h\&.
.SS "#define ENOSTR   60	/* Device not a stream */"

.PP
Definition at line 186 of file errno\&.h\&.
.SS "#define ENOSYS   38	/* Function not implemented */"

.PP
Definition at line 162 of file errno\&.h\&.
.SS "#define ENOTBLK   15	/* Block device required */"

.PP
Definition at line 139 of file errno\&.h\&.
.SS "#define ENOTCONN   107	/* Transport endpoint is not connected */"

.PP
Definition at line 233 of file errno\&.h\&.
.SS "#define ENOTDIR   20	/* Not a directory */"

.PP
Definition at line 144 of file errno\&.h\&.
.SS "#define ENOTEMPTY   39	/* Directory not empty */"

.PP
Definition at line 163 of file errno\&.h\&.
.SS "#define ENOTNAM   118	/* Not a XENIX named type file */"

.PP
Definition at line 244 of file errno\&.h\&.
.SS "#define ENOTRECOVERABLE   131	/* State not recoverable */"

.PP
Definition at line 260 of file errno\&.h\&.
.SS "#define ENOTSOCK   88	/* Socket operation on non-socket */"

.PP
Definition at line 214 of file errno\&.h\&.
.SS "#define ENOTTY   25	/* Not a typewriter */"

.PP
Definition at line 149 of file errno\&.h\&.
.SS "#define ENOTUNIQ   76	/* Name not unique on network */"

.PP
Definition at line 202 of file errno\&.h\&.
.SS "#define ENXIO   6	/* No such device or address */"

.PP
Definition at line 130 of file errno\&.h\&.
.SS "#define EOKAY   0  /* No error */"

.PP
Definition at line 124 of file errno\&.h\&.
.SS "#define EOPNOTSUPP   95	/* Operation not supported on transport endpoint */"

.PP
Definition at line 221 of file errno\&.h\&.
.SS "#define EOVERFLOW   75	/* Value too large for defined data type */"

.PP
Definition at line 201 of file errno\&.h\&.
.SS "#define EOWNERDEAD   130	/* Owner died */"

.PP
Definition at line 259 of file errno\&.h\&.
.SS "#define EPERM   1	/* Operation not permitted */"

.PP
Definition at line 125 of file errno\&.h\&.
.SS "#define EPFNOSUPPORT   96	/* Protocol family not supported */"

.PP
Definition at line 222 of file errno\&.h\&.
.SS "#define EPIPE   32	/* Broken pipe */"

.PP
Definition at line 156 of file errno\&.h\&.
.SS "#define EPROTO   71	/* Protocol error */"

.PP
Definition at line 197 of file errno\&.h\&.
.SS "#define EPROTONOSUPPORT   93	/* Protocol not supported */"

.PP
Definition at line 219 of file errno\&.h\&.
.SS "#define EPROTOTYPE   91	/* Protocol wrong type for socket */"

.PP
Definition at line 217 of file errno\&.h\&.
.SS "#define ERANGE   0x03"

.PP
Definition at line 158 of file errno\&.h\&.
.SS "#define ERANGE   34	/* Math result not representable */"

.PP
Definition at line 158 of file errno\&.h\&.
.SS "#define EREMCHG   78	/* Remote address changed */"

.PP
Definition at line 204 of file errno\&.h\&.
.SS "#define EREMOTE   66	/* Object is remote */"

.PP
Definition at line 192 of file errno\&.h\&.
.SS "#define EREMOTEIO   121	/* Remote I/O error */"

.PP
Definition at line 247 of file errno\&.h\&.
.SS "#define ERESTART   85	/* Interrupted system call should be restarted */"

.PP
Definition at line 211 of file errno\&.h\&.
.SS "#define ERFKILL   132	/* Operation not possible due to RF-kill */"

.PP
Definition at line 262 of file errno\&.h\&.
.SS "#define EROFS   30	/* Read-only file system */"

.PP
Definition at line 154 of file errno\&.h\&.
.SS "#define errno   (*\fB__errno\fP())"

.PP
Definition at line 268 of file errno\&.h\&.
.SS "#define errno   \fB__errno\fP"

.PP
Definition at line 268 of file errno\&.h\&.
.SS "#define ESHUTDOWN   108	/* Cannot send after transport endpoint shutdown */"

.PP
Definition at line 234 of file errno\&.h\&.
.SS "#define ESOCKTNOSUPPORT   94	/* Socket type not supported */"

.PP
Definition at line 220 of file errno\&.h\&.
.SS "#define ESPIPE   29	/* Illegal seek */"

.PP
Definition at line 153 of file errno\&.h\&.
.SS "#define ESRCH   3	/* No such process */"

.PP
Definition at line 127 of file errno\&.h\&.
.SS "#define ESRMNT   69	/* Srmount error */"

.PP
Definition at line 195 of file errno\&.h\&.
.SS "#define ESTALE   116	/* Stale NFS file handle */"

.PP
Definition at line 242 of file errno\&.h\&.
.SS "#define ESTRPIPE   86	/* Streams pipe error */"

.PP
Definition at line 212 of file errno\&.h\&.
.SS "#define ETIME   62	/* Timer expired */"

.PP
Definition at line 188 of file errno\&.h\&.
.SS "#define ETIMEDOUT   110	/* Connection timed out */"

.PP
Definition at line 236 of file errno\&.h\&.
.SS "#define ETOOMANYREFS   109	/* Too many references: cannot splice */"

.PP
Definition at line 235 of file errno\&.h\&.
.SS "#define ETXTBSY   26	/* Text file busy */"

.PP
Definition at line 150 of file errno\&.h\&.
.SS "#define EUCLEAN   117	/* Structure needs cleaning */"

.PP
Definition at line 243 of file errno\&.h\&.
.SS "#define EUNATCH   49	/* Protocol driver not attached */"

.PP
Definition at line 173 of file errno\&.h\&.
.SS "#define EUSERS   87	/* Too many users */"

.PP
Definition at line 213 of file errno\&.h\&.
.SS "#define EWOULDBLOCK   \fBEAGAIN\fP	/* Operation would block */"

.PP
Definition at line 165 of file errno\&.h\&.
.SS "#define EXDEV   18	/* Cross-device link */"

.PP
Definition at line 142 of file errno\&.h\&.
.SS "#define EXFULL   54	/* Exchange full */"

.PP
Definition at line 178 of file errno\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBerrno_t\fP"

.PP
Definition at line 266 of file errno\&.h\&.
.SH "Function Documentation"
.PP 
.SS "volatile int* __errno (void)"

.SS "void perror (char *s)"

.PP
Definition at line 33 of file errno\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBerrno_t\fP __errno"

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
