.TH "include/caribou/lib/fault.h" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/caribou/lib/fault.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__attribute__\fP ((naked)) void _hard_fault(void)"
.br
.RI "\fIThe tick interrupt handler (jiffy counting) \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void __attribute__ ((naked))"

.PP
The tick interrupt handler (jiffy counting) The tick interrupt handler (jiffy counting) 
.PP
Definition at line 681 of file thread\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
