.TH "src/dev/gpio.c" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dev/gpio.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/dev/gpio\&.h>\fP
.br
\fC#include <chip/gpio\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
