.TH "src/kernel/interrupt.c" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kernel/interrupt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/kernel/interrupt\&.h>\fP
.br
\fC#include <caribou/lib/heap\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcaribou_interrupt_handler_s\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct 
.br
\fBcaribou_interrupt_handler_s\fP \fBcaribou_interrupt_handler_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static int \fBisr_map_extend\fP (int size)"
.br
.ti -1c
.RI "int \fBcaribou_vector_installed\fP (InterruptVector vector, \fBcaribou_isr_t\fP isr, void *arg)"
.br
.RI "\fIDetermine if a vector is already installed\&. \fP"
.ti -1c
.RI "int \fBcaribou_vector_install\fP (InterruptVector vector, \fBcaribou_isr_t\fP isr, void *arg)"
.br
.RI "\fIInstall the vector into the isr_map chain\&. \fP"
.ti -1c
.RI "int \fBcaribou_vector_remove\fP (InterruptVector vector, \fBcaribou_isr_t\fP isr)"
.br
.RI "\fIInstall the vector into the isr_map chain\&. \fP"
.ti -1c
.RI "int \fBcaribou_vector_remove_all\fP (void *arg)"
.br
.RI "\fIRemove all vectors associated with arg\&. \fP"
.ti -1c
.RI "\fB__attribute__\fP ((weak))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcaribou_interrupt_handler_t\fP ** \fBisr_map\fP = \fBNULL\fP"
.br
.ti -1c
.RI "int \fBisr_map_size\fP = 0"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBcaribou_interrupt_handler_s\fP  \fBcaribou_interrupt_handler_t\fP"

.SH "Function Documentation"
.PP 
.SS "__attribute__ ((weak))"
Interrupt service entry point 
.PP
Definition at line 185 of file interrupt\&.c\&.
.SS "int caribou_vector_install (InterruptVectorvector, \fBcaribou_isr_t\fPisr, void *arg)"

.PP
Install the vector into the isr_map chain\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvector\fP The device specific interrupt vector number\&. 
.br
\fIisr\fP A pointer to the interrupt service routing for the vector\&. 
.br
\fIarg\fP An optional argument to pass to the interrupt handler\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The vector number or < 0 on failure\&. 
.RE
.PP

.PP
Definition at line 84 of file interrupt\&.c\&.
.SS "int caribou_vector_installed (InterruptVectorvector, \fBcaribou_isr_t\fPisr, void *arg)"

.PP
Determine if a vector is already installed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvector\fP The device specific interrupt vector number\&. 
.br
\fIisr\fP A pointer to the interrupt service routing for the vector\&. 
.br
\fIarg\fP An optional argument to pass to the interrupt handler\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
non-zero if vector is installed\&. 
.RE
.PP

.PP
Definition at line 56 of file interrupt\&.c\&.
.SS "int caribou_vector_remove (InterruptVectorvector, \fBcaribou_isr_t\fPisr)"

.PP
Install the vector into the isr_map chain\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvector\fP The device specific interrupt vector number\&. 
.br
\fIisr\fP A pointer to the interrupt service routing for the vector\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The vector number or < 0 on failure\&. 
.RE
.PP

.PP
Definition at line 121 of file interrupt\&.c\&.
.SS "int caribou_vector_remove_all (void *arg)"

.PP
Remove all vectors associated with arg\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvector\fP The device specific interrupt vector number\&. 
.br
\fIarg\fP A pointer to the arg 
.RE
.PP
\fBReturns:\fP
.RS 4
The vector number or < 0 on failure\&. 
.RE
.PP

.PP
Definition at line 154 of file interrupt\&.c\&.
.SS "static int isr_map_extend (intsize)\fC [static]\fP"
extend the size of the isr map table 
.PP
Definition at line 31 of file interrupt\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBcaribou_interrupt_handler_t\fP** isr_map = \fBNULL\fP"

.PP
Definition at line 27 of file interrupt\&.c\&.
.SS "int isr_map_size = 0"

.PP
Definition at line 28 of file interrupt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
