.TH "src/lib/rand.c" 3 "Sat Jul 19 2014" "Version 0.9" "CARIBOU RTOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib/rand.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <caribou/kernel/thread\&.h>\fP
.br
\fC#include <chip/chip\&.h>\fP
.br
\fC#include <cpu/cpu\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsrand\fP (uint32_t seed)"
.br
.ti -1c
.RI "uint32_t \fBrand\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static uint32_t \fBrand_next\fP =0xA0A0A0A0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t rand ()"

.PP
Definition at line 33 of file rand\&.c\&.
.SS "void srand (uint32_tseed)"

.PP
Definition at line 28 of file rand\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "uint32_t rand_next =0xA0A0A0A0\fC [static]\fP"

.PP
Definition at line 26 of file rand\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CARIBOU RTOS from the source code\&.
