#ifndef _GU8_MODE_STATUS_H_
#define _GU8_MODE_STATUS_H_

#define STATUS_INTERVAL	4000

typedef enum {
  STATUS_AIRFLOW_LINEAR_CONTEXT_ID = 1,
  STATUS_AIRFLOW_VOLUME_CONTEXT_ID,
  STATUS_INTERNAL_TEMPERATURE_CONTEXT_ID,
  STATUS_PRESS_CONTEXT_ID,
  STATUS_SETUP_CONTEXT_ID,
  STATUS_CONTEXT_ID,
} gu8_status_context_id_t;

gu8_context_t status_mode_contexts[STATUS_CONTEXT_ID];

#endif
